config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:index, :new, :create]
  end
  resources :doses, only: [:destroy]
  resources :cocktails, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :doses, dependent: :destroy
    has_many :ingredients, through: :doses

    validates :name, presence: true, uniqueness: true

    mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates_uniqueness_of :ingredient, scope: :cocktail_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :doses

    validates :name, presence: true, uniqueness: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    def index
        @cocktails = Cocktail.all
    end

    def show
        @cocktail = Cocktail.find(params[:id])
    end

    def new
        @cocktail = Cocktail.new
    end

    def create
        @cocktail = Cocktail.new(cocktail_params)
        if @cocktail.save
            redirect_to cocktail_path(@cocktail)
        else
            render :new
        end
    end

    def destroy
        @cocktail = Cocktail.find(params[:id])
        @cocktail.destroy
        redirect_to cocktails_path(@cocktails)
      end

    private

    def cocktail_params
        params.require(:cocktail).permit(:name, :photo)
    end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def index
    @doses = Dose.all
  end
  
  def show
    @dose = Dose.find(params[:id])
  end
  
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end
  
  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail_id)
  end
  
  private
  
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <%= audio_tag "top_gun.mp3", id: "sound", class: "audio-to-play", autoplay: :true %>
  <!-- <div class="headings">
    <h1>Wooop! <strong>Cock</strong>tail <strong>O'Clock!</strong></h1>

    <p><span id="banner-typed-text"></span></p>

    <%#= link_to "Want to add your own cocktail!?", new_cocktail_path(@cocktail), class: "buttons btn btn-danger"%>
  </div>

  <div class="row">
  <%# @cocktails.each do |cocktail| %>
    <div class="col-sm-6 col-md-4 col-lg-3">
      <div class="card-outline">
        <div class="card-content card-image">
          <%#= cl_image_tag cocktail.photo, height: 165, width: 270, crop: :fill %>
        </div>
        <div class="card-content card-body">
          <div>
            <%#= link_to cocktail.name, cocktail_path(cocktail), class: "cocktail-name" %>
          </div>
          <div>
            <%#= link_to cocktail_path(cocktail.id),
                  method: :delete,
                  data: { confirm: 'Are you sure?'} do %>
                  <i class="button far fa-trash-alt"></i>
                  <%# end %>
          </div>
        </div>
      </div>
    </div>
  <%# end %>
  </div> -->
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="form">  
    <%= simple_form_for @cocktail do |f| %>
      <%= f.input :name %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/cocktails/show.html.erb
<div>
    <h1 class="title">Check out this great Cocktail!</h1>
    <h3 class="drink"><%= @cocktail.name %></h3>
    <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

    <h4>Make one!</h4>
    <div class="ingredients_list">
      <% @cocktail.doses.each do |dose| %>
        <p><%= dose.description %> of:</p>
        <ul>
        <li><%= dose.ingredient.name %>
        <%= link_to "", dose_path(dose), 
            method: :delete, 
            data: { confirm: 'Are you sure?' }, class: "button far fa-trash-alt" %>
            </li>
        </ul>
      <% end %>
    </div>


    <div class="buttons">
      <div>
        <%= link_to "back to booze", cocktails_path(@cocktail), class: "btn btn-warning" %>
      </div>
      <br>
      <div>
        <%= link_to "add some boozey ingredients", new_cocktail_dose_path(@cocktail.id), class: "btn btn-success" %>
      </div>
    </div>
</div>

app/views/doses/new.html.erb
<h1>Create a New Dose</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.label :description %>
    <%= f.select :description, ['a handful', 'a pinch', 'a shit ton'] %>
    <%= f.association :ingredient %>
    <%= f.submit %>
 <%= link_to "back to cocktail", cocktail_path(@cocktail.id) %>
<% end %>

app/views/doses/show.html.erb
<div>
    <h1>Doses!</h1>

    <%= link_to "add a dose", cocktail_doses_path(@dose) %>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag 'logo.jpg' %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link">Add a drink</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Home</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>

    <%#= render 'layouts/footer' %>
    <%= javascript_pack_tag "application"%>
  </body>
</html>